version: "3"
services:
  app:
    build: .
    image: jifblog
    environment:
      PYTHONUNBUFFERED: "true"
    env_file: configuration.env
    command: ./start_app.sh
    ports:
      - "8000:8000"
    volumes:
      - ./database:/srv/app/database
      - ./media:/srv/app/media
      - ./static:/srv/app/static

  nginx:
      image: nginx
      environment:
        VIRTUAL_HOST: "jifblog.com"
        VIRTUAL_PORT: 80
      ports:
        - "80:80"
      depends_on:
        - app
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./media:/srv/public/media:ro
        - ./static:/srv/public/static:ro
