# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import feed.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GifImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=feed.utils.UploadToPathWithUUID('iamges'))),
            ],
        ),
    ]
