# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import feed.utils


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifimage',
            name='bgcolor',
            field=models.CharField(default='ff00ff', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gifimage',
            name='image',
            field=models.ImageField(upload_to=feed.utils.UploadToPathWithUUID('images')),
        ),
    ]
