# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20171112_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifimage',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
