# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_gifimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifimage',
            name='caption',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gifimage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
